# ---- Base Node ----
FROM node:15.5.0 AS base
RUN mkdir -p /usr/src
WORKDIR /usr/src
COPY package.json .

#
# ---- Dependencies ----
FROM base AS dependencies
# install node packages
RUN npm set progress=false && npm config set depth 0
RUN npm install --only=production
# copy production node_modules aside
RUN cp -R node_modules prod_node_modules
# install ALL node_modules, including 'devDependencies'
RUN npm install

#
# ---- Release ----
FROM base AS release
# copy production node_modules
COPY --from=dependencies /usr/src/prod_node_modules ./node_modules
# copy app sources
COPY . .
# expose port and define CMD
RUN npm run build
EXPOSE 3000
CMD npm run start
