version: '3'

services:
  beady-eye:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - serv_network
networks:
  serv_network:
    external: true
